# Generated by Django 2.1.5 on 2020-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
