# Generated by Django 2.1.5 on 2020-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
